import { useState } from 'react'
import { ArrowUpRight, ShoppingBag, Menu, Plus, Sparkles, UserRound, X } from 'lucide-react'
import heroImage from '../assets/luxury-stop-after-hours.png'
import ritualImage from '../assets/luxury-stop-hero.png'

 const products=[
  {id:1,name:'Noir Truffle Collection',type:'72% cacao / 12 pieces',price:895,color:'#403027',image:heroImage},
  {id:2,name:'Olive Milk Soap',type:'Cold process / 100g',price:395,color:'#737962',image:ritualImage},
  {id:3,name:'The Evening Gift Box',type:'Chocolate, ritual & a note',price:1495,color:'#a47952',image:heroImage}]

export default function App(){
 const [bag,setBag]=useState([]),[selected,setSelected]=useState(products[0]),[giftOpen,setGiftOpen]=useState(false),[bagOpen,setBagOpen]=useState(false),[accountOpen,setAccountOpen]=useState(false),[collectionOpen,setCollectionOpen]=useState(false),[message,setMessage]=useState('')
 const add=p=>{setBag([...bag,p]);setMessage(`${p.name} is in your bag`);setTimeout(()=>setMessage(''),2600)}
 return <><div className="ticker"><span>COMPLIMENTARY GIFT WRAP</span><i>✦</i><span>FREE DELIVERY ABOVE ₹1,500</span><i>✦</i><span>MADE FOR DELIGHTFUL DAYS</span></div>
 <header><button className="mobile-menu"><Menu size={20}/></button><nav><button className="nav-link" onClick={()=>setCollectionOpen(true)}>Collections</button><a href="#gifts">Gifting</a><a href="#story">Our story</a></nav><a className="wordmark" href="#home">LUXURY <em>STOP</em></a><div className="utilities"><button className="plain-button">Search</button><button className="account-button" onClick={()=>setAccountOpen(true)}><UserRound size={17}/><span>Account</span></button><button className="bag" onClick={()=>setBagOpen(true)}><ShoppingBag size={18}/><span>Bag</span><b>{bag.length}</b></button></div></header>
 <main id="home"><section className="hero"><div className="hero-copy"><p className="kicker"><Sparkles size={13}/> An everyday study in pleasure</p><h1>Small rituals,<br/><i>beautifully kept.</i></h1><p>Thoughtfully made sweets, tactile bathing rituals and gifts with a certain kind of quiet confidence.</p><div className="hero-actions"><a className="button dark" href="#shop">Explore the collection <ArrowUpRight size={16}/></a><button className="text-link" onClick={()=>setGiftOpen(true)}>Curate a gift <span>→</span></button></div><div className="flavour-note"><span>01</span><p>In the house today<br/><b>Cacao, olive &amp; rose</b></p></div></div><div className="hero-media"><div className="hero-shape one"></div><div className="hero-shape two"></div><img src={heroImage} alt="Luxury Stop gift box with chocolates and artisanal soap"/><div className="hero-sticker">A little<br/><em>more considered.</em><small>• made slowly, given gladly •</small></div><button className="floating-product" onClick={()=>add(products[0])}><i></i><span><b>Noir truffles</b><small>Add to bag</small></span><Plus size={17}/></button></div></section>
 <section className="ritual-strip"><span>SMALL-BATCH</span><span>✦</span><b>Made in India</b><span>✦</span><span>FOR SLOW MOMENTS</span></section>
 <section className="shop-section" id="shop"><div className="section-intro"><p className="kicker">A collection for the senses</p><h2>Quiet things,<br/><i>with presence.</i></h2><p>Every piece is made to leave a soft, considered impression.</p></div><div className="mood-grid"><button className="mood cocoa" onClick={()=>setCollectionOpen(true)}><span>For the<br/><i>sweet tooth</i></span><b>Confectionery <ArrowUpRight/></b></button><button className="mood rose" onClick={()=>setCollectionOpen(true)}><span>For the<br/><i>daily ritual</i></span><b>Bath &amp; body <ArrowUpRight/></b></button><button className="mood citrus" onClick={()=>setCollectionOpen(true)}><span>For the<br/><i>thoughtful gesture</i></span><b>Gift boxes <ArrowUpRight/></b></button></div><button className="collection-cta" onClick={()=>setCollectionOpen(true)}>View the full collection <ArrowUpRight size={17}/></button></section>
 <section className="shop-edit"><div className="edit-header"><div><p className="kicker">The material edit</p><h2>Made to linger,<br/><i>not to shout.</i></h2></div><p>Choose a ritual, discover its texture and take a more considered moment home.</p></div><div className="product-showcase"><div className="palette"><p>Choose a ritual</p>{products.map(p=><button key={p.id} onClick={()=>setSelected(p)} className={selected.id===p.id?'active':''}><i style={{background:p.color}}></i><span>{p.name.split(' ')[0]}</span></button>)}</div><div className="featured-product" style={{'--product-color':selected.color}}><div className="product-glow"></div><img src={selected.image} alt={selected.name}/><span className="rotate-copy">LUXURY STOP • MADE FOR SLOW MOMENTS • </span></div><div className="product-detail"><span className="edition">THE MATERIAL EDIT / 01</span><h3>{selected.name}</h3><p>{selected.type}</p><strong>₹{selected.price}</strong><div className="swatches"><i style={{background:selected.color}}></i><i style={{background:'#ede5d7'}}></i><i style={{background:'#6c725e'}}></i></div><button onClick={()=>add(selected)} className="button dark">Add to bag <Plus size={16}/></button></div></div></section>
 <section className="gift-banner" id="gifts"><div className="gift-visual"><div className="ribbon r1"></div><div className="ribbon r2"></div><div className="gift-card">A thoughtful<br/><i>little thing.</i><small>PERSONALISE YOUR GIFT</small></div></div><div className="gift-content"><p className="kicker">For every “this made me think of you”</p><h2>Gifting, <i>but make it personal.</i></h2><p>Choose the treats. Choose the feeling. Add a handwritten note. We’ll wrap the moment up just right.</p><button className="button light" onClick={()=>setGiftOpen(true)}>Start building <ArrowUpRight size={16}/></button></div></section>
 <section className="story" id="story"><p className="kicker">Luxury Stop, in a nutshell</p><div className="story-content"><h2>We believe in a daily dose of <i>more.</i></h2><p>More care in the details. More feeling in the giving. More permission to make a Tuesday afternoon feel like an occasion.</p><a href="#home" className="text-link">Read our story <span>→</span></a></div></section>
 <section className="newsletter"><div><p className="kicker">A note from the good stuff department</p><h2>First dibs on<br/><i>beautiful things.</i></h2></div><form onSubmit={e=>{e.preventDefault();setMessage('Welcome to the good stuff ✦')}}><input required aria-label="Email address" type="email" placeholder="Your email address"/><button type="submit">Sign me up <ArrowUpRight size={17}/></button><small>Small drops, gift ideas and no boring emails.</small></form></section></main>
 <footer><a className="wordmark" href="#home">LUXURY <em>STOP</em></a><p>Confectionery · Bath · Thoughtful gifting</p><div><a href="#shop">Shop</a><a href="#gifts">Gift cards</a><a href="#story">Instagram</a></div><small>© 2026 Luxury Stop. Crafted for the joy of it.</small></footer>
 {message&&<div className="toast">{message}<button onClick={()=>setMessage('')}><X size={16}/></button></div>}{giftOpen&&<GiftBuilder onClose={()=>setGiftOpen(false)} onAdd={g=>{add({...g,price:1495});setGiftOpen(false)}}/>}{bagOpen&&<BagDrawer bag={bag} onClose={()=>setBagOpen(false)} onRemove={index=>setBag(bag.filter((_,itemIndex)=>itemIndex!==index))}/>} {accountOpen&&<AccountPage onClose={()=>setAccountOpen(false)} onSuccess={text=>{setAccountOpen(false);setMessage(text)}}/>}{collectionOpen&&<CollectionPage onClose={()=>setCollectionOpen(false)} onAdd={add}/>}</>}
function GiftBuilder({onClose,onAdd}){const[step,setStep]=useState(0);const picks=[['Pick your box','The blush box','The saffron box'],['Add some joy','Raspberry bar','Rose cloud soap'],['Make it personal','For you, with love','Just because']];return <div className="modal-backdrop"><div className="gift-modal"><button className="close" onClick={onClose}><X/></button><p className="kicker">Build your gift / 0{step+1}</p><div className="progress"><i style={{width:`${(step+1)*33}%`}}></i></div><h2>{picks[step][0]}<br/><i>Make it feel like them.</i></h2><div className="gift-choices">{picks[step].slice(1).map((p,i)=><button key={p} className={i===0?'chosen':''}>{p}<Plus size={16}/></button>)}</div><button className="button dark" onClick={()=>step<2?setStep(step+1):onAdd({name:'Your custom joy box'})}>{step<2?'Continue':'Add my gift box'}<ArrowUpRight size={16}/></button></div></div>}
function BagDrawer({bag,onClose,onRemove}){const total=bag.reduce((sum,item)=>sum+(item.price||0),0);return <div className="bag-overlay" onClick={onClose}><aside className="bag-drawer" onClick={event=>event.stopPropagation()}><div className="bag-title"><div><p className="kicker">Your selection</p><h2>Bag <i>({bag.length})</i></h2></div><button className="close" onClick={onClose}><X/></button></div>{bag.length?<><div className="bag-items">{bag.map((item,index)=><div className="bag-item" key={`${item.name}-${index}`}><div className="bag-thumb" style={{background:item.color}}>{item.image&&<img src={item.image} alt=""/>}</div><div><h3>{item.name}</h3><p>{item.type||'Curated especially for you'}</p><strong>₹{item.price.toLocaleString('en-IN')}</strong></div><button className="remove" onClick={()=>onRemove(index)}>Remove</button></div>)}</div><div className="bag-summary"><p><span>Subtotal</span><strong>₹{total.toLocaleString('en-IN')}</strong></p><small>Complimentary wrapping included.</small><button className="button dark">Proceed to checkout <ArrowUpRight size={16}/></button></div></>:<div className="empty-bag"><ShoppingBag size={28}/><h3>Your bag is waiting.</h3><p>There’s room for a lovely little thing.</p><button className="button dark" onClick={onClose}>Explore collection</button></div>}</aside></div>}
function AccountPage({onClose,onSuccess}){const[mode,setMode]=useState('signin');const signUp=mode==='signup';return <div className="account-page"><div className="account-visual"><img src={heroImage} alt="Luxury Stop’s evening collection"/><div className="account-quote"><span>THE PRIVATE EDIT</span><p>“Good things,<br/><i>remembered.”</i></p><small>MEMBERS RECEIVE FIRST ACCESS TO NEW DROPS</small></div></div><section className="account-panel"><button className="account-close" onClick={onClose}><X size={20}/><span>Close</span></button><a className="wordmark" href="#home">LUXURY <em>STOP</em></a><div className="account-form"><p className="kicker">{signUp?'Begin your private edit':'Welcome back'}</p><h1>{signUp?'A little more,':'The good things,'}<br/><i>{signUp?'just for you.':'saved for you.'}</i></h1><p className="account-intro">{signUp?'Create an account for saved rituals, considered gifting and first access to new collections.':'Sign in to find your saved rituals, gift notes and previous orders.'}</p><form onSubmit={event=>{event.preventDefault();onSuccess(signUp?'Your private edit is ready ✦':'Welcome back to Luxury Stop ✦')}}>{signUp&&<label>Full name<input required placeholder="Your name"/></label>}<label>Email address<input required type="email" placeholder="you@example.com"/></label><label>Password<input required type="password" placeholder="••••••••"/></label>{!signUp&&<button type="button" className="forgot">Forgot password?</button>}<button className="button dark" type="submit">{signUp?'Create my account':'Sign in'} <ArrowUpRight size={16}/></button></form><div className="account-switch"><span>{signUp?'Already have an account?':'New to Luxury Stop?'}</span><button onClick={()=>setMode(signUp?'signin':'signup')}>{signUp?'Sign in':'Create an account'} →</button></div></div><div className="account-footer"><span>PRIVATE EDITS</span><i>✦</i><span>THOUGHTFUL GIFTING</span></div></section></div>}
function CollectionPage({onClose,onAdd}){const[filter,setFilter]=useState('All');const items=[...products,{id:4,name:'Rosewater Bonbons',type:'White chocolate / 9 pieces',price:745,color:'#9b6460',image:ritualImage,group:'Sweets'},{id:5,name:'Moss Bath Soak',type:'Mineral salt soak / 280g',price:645,color:'#68705f',image:heroImage,group:'Rituals'},{id:6,name:'A Note, In Ivory',type:'Gift set / ready to send',price:1695,color:'#aa957f',image:ritualImage,group:'Gifting'}].map((item,index)=>({...item,group:item.group||(['Sweets','Rituals','Gifting'][index])}));const visible=filter==='All'?items:items.filter(item=>item.group===filter);return <div className="collection-page"><header className="collection-header"><a className="wordmark" href="#home">LUXURY <em>STOP</em></a><button onClick={onClose}><X size={19}/><span>Close collection</span></button></header><section className="collection-hero"><div><p className="kicker">The house collection / 01</p><h1>Things worth<br/><i>returning to.</i></h1><p>A considered curation of sweets, daily rituals and gestures made to say more.</p></div><div className="collection-hero-image"><img src={heroImage} alt="Luxury Stop collection"/><span>SCROLL TO DISCOVER</span></div></section><section className="collection-body"><div className="collection-toolbar"><p>{visible.length} pieces, collected slowly</p><div>{['All','Sweets','Rituals','Gifting'].map(item=><button key={item} className={filter===item?'selected':''} onClick={()=>setFilter(item)}>{item}</button>)}</div></div><div className="collection-grid">{visible.map((item,index)=><article className={`collection-card card-${index%3}`} key={item.id}><div className="collection-image" style={{background:item.color}}><span>{item.group}</span><img src={item.image} alt={item.name}/><button onClick={()=>onAdd(item)} aria-label={`Add ${item.name}`}><Plus size={17}/></button></div><div className="collection-detail"><div><h3>{item.name}</h3><p>{item.type}</p></div><strong>₹{item.price.toLocaleString('en-IN')}</strong></div></article>)}</div></section></div>}
