import { useEffect, useState } from 'react'
import { ArrowUpRight, ShoppingBag, Menu, Plus, Sparkles, UserRound, X } from 'lucide-react'
import heroImage from '../assets/luxury-stop-after-hours.png'
import ritualImage from '../assets/luxury-stop-hero.png'
import perfumeImage from '../assets/perfume-noir.png'
import sunglassesImage from '../assets/sunglasses-noir.png'
import handbagImage from '../assets/handbag-noir.png'
import watchNoir from '../assets/watch-noir.png'
import watchChampagne from '../assets/watch-champagne.png'
import watchSilver from '../assets/watch-silver.png'
import spotlightImage from '../assets/style-spotlight.png'
import gucciLogo from '../assets/logos/gucci.svg'
import zaraLogo from '../assets/logos/zara.svg'
import charlesKeithLogo from '../assets/logos/charles-keith.svg'
import versaceLogo from '../assets/logos/versace.svg'
import rayBanLogo from '../assets/logos/ray-ban.svg'
import aldoLogo from '../assets/logos/aldo.svg'

 const products=[
  {id:1,name:'Noir Truffle Collection',type:'72% cacao / 12 pieces',price:895,color:'#403027',image:heroImage},
  {id:2,name:'Olive Milk Soap',type:'Cold process / 100g',price:395,color:'#737962',image:ritualImage},
  {id:3,name:'The Evening Gift Box',type:'Chocolate, ritual & a note',price:1495,color:'#a47952',image:heroImage}]

const accessoryProducts=[
 {id:'p-01',brand:'GUCCI',name:'Guilty Elixir',type:'Eau de parfum · 60ml',price:13700,color:'#715747',image:perfumeImage,position:'50% 50%',crop:'single',category:'Perfumes',details:'A deep, warm fragrance profile with floral and woody character for evenings.'},
 {id:'p-02',brand:'RAY-BAN',name:'Wayfarer Noir',type:'Hand-finished acetate',price:12490,color:'#302d2a',image:sunglassesImage,position:'50% 50%',crop:'single',category:'Glares',details:'Iconic black acetate frames with smoke-grey UV lenses and a tailored fit.'},
 {id:'p-03',brand:'CHARLES & KEITH',name:'Gabine Mini',type:'Structured leather handbag',price:13999,color:'#66594e',image:handbagImage,position:'50% 50%',crop:'single',category:'Handbags',details:'A softly structured everyday bag with polished hardware and an adjustable strap.'},
 {id:'p-04',brand:'ZARA',name:'Red Vanilla Elixir',type:'Eau de parfum · 100ml',price:3950,color:'#9b6b58',image:perfumeImage,position:'50% 50%',crop:'single',category:'Perfumes',details:'A modern amber fragrance with a warm vanilla dry-down and an expressive finish.'},
 {id:'p-05',brand:'GUCCI',name:'Cat-Eye Frame',type:'Acetate sunglasses',price:24990,color:'#4a4037',image:sunglassesImage,position:'50% 50%',crop:'single',category:'Glares',details:'Graphic cat-eye sunglasses designed with dark lenses and an elevated profile.'},
 {id:'p-06',brand:'ZARA',name:'Oval Shoulder Bag',type:'Textured shoulder bag',price:3550,color:'#856d56',image:handbagImage,position:'50% 50%',crop:'single',category:'Handbags',details:'A compact shoulder silhouette in tactile leather-effect material.'},
 {id:'p-07',brand:'VERSACE',name:'Crystal Noir',type:'Eau de toilette · 90ml',price:9950,color:'#4b3d48',image:perfumeImage,position:'50% 50%',crop:'single',category:'Perfumes',details:'A polished floral fragrance with a darker, softly spiced signature.'},
 {id:'p-08',brand:'POLAROID',name:'Metallic Aviator',type:'Polarised sunglasses',price:6299,color:'#53504c',image:sunglassesImage,position:'50% 50%',crop:'single',category:'Glares',details:'Lightweight metal aviators with polarised lenses for everyday clarity.'},
 {id:'p-09',brand:'ALDO',name:'Luxe Top Handle',type:'Mini top-handle handbag',price:8999,color:'#52443b',image:handbagImage,position:'50% 50%',crop:'single',category:'Handbags',details:'A refined mini bag with a top handle, detachable strap and gold-tone closure.'},
 {id:'p-10',brand:'EMPORIO ARMANI',name:'Noir Leather Timepiece',type:'Quartz movement · 42mm',price:18990,color:'#282523',image:watchNoir,position:'50% 50%',crop:'single',category:'Watches',details:'A refined black leather timepiece with a dark sunray dial and understated polished case.'},
 {id:'p-11',brand:'VERSACE',name:'Champagne Icon',type:'Stainless-steel bracelet · 36mm',price:32990,color:'#b69a67',image:watchChampagne,position:'50% 50%',crop:'single',category:'Watches',details:'A luminous champagne-tone bracelet watch designed to bring a polished finish to every look.'},
 {id:'p-12',brand:'FOSSIL',name:'Silver Chronograph',type:'Chronograph movement · 44mm',price:15495,color:'#4d4c49',image:watchSilver,position:'50% 50%',crop:'single',category:'Watches',details:'A versatile silver chronograph with a charcoal dial, sculpted lugs and a tailored metal bracelet.'}]

const brandLogos=[['Gucci',gucciLogo],['Zara',zaraLogo],['Charles & Keith',charlesKeithLogo],['Versace',versaceLogo],['Ray-Ban',rayBanLogo],['Aldo',aldoLogo]]

export default function App(){
 const [bag,setBag]=useState([]),[selected,setSelected]=useState(products[0]),[giftOpen,setGiftOpen]=useState(false),[bagOpen,setBagOpen]=useState(false),[accountOpen,setAccountOpen]=useState(false),[productOpen,setProductOpen]=useState(null),[menuOpen,setMenuOpen]=useState(false),[message,setMessage]=useState(''),[route,setRoute]=useState(window.location.hash==='#/collections'?'collections':'home')
 const add=p=>{setBag([...bag,p]);setMessage(`${p.name} is in your bag`);setTimeout(()=>setMessage(''),2600)}
 useEffect(()=>{const sync=()=>setRoute(window.location.hash==='#/collections'?'collections':'home');window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[])
 const goCollection=()=>{window.location.hash='/collections';setRoute('collections')}
 const goHome=()=>{window.location.hash='home';setRoute('home')}
 const setCollectionOpen=goCollection
 if(route==='collections')return <><CatalogPage onClose={goHome} onView={setProductOpen}/>{productOpen&&<ProductPage product={productOpen} onClose={()=>setProductOpen(null)} onAdd={quantity=>{for(let item=0;item<quantity;item+=1)add(productOpen);setProductOpen(null)}}/>}</>
 return <><div className="ticker"><span>COMPLIMENTARY GIFT WRAP</span><i>✦</i><span>FREE DELIVERY ABOVE ₹1,500</span><i>✦</i><span>MADE FOR DELIGHTFUL DAYS</span></div>
 <header><button className="mobile-menu" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Open menu"><Menu size={20}/></button><nav className={menuOpen?'mobile-open':''}><button className="nav-link" onClick={()=>{goCollection();setMenuOpen(false)}}>Collections</button><a href="#accessories" onClick={()=>setMenuOpen(false)}>Accessories</a><a href="#brands" onClick={()=>setMenuOpen(false)}>Brands</a><a href="#story" onClick={()=>setMenuOpen(false)}>Our story</a></nav><a className="wordmark" href="#home">LUXURY <em>STOP</em></a><div className="utilities"><button className="plain-button">Search</button><button className="account-button" onClick={()=>setAccountOpen(true)}><UserRound size={17}/><span>Account</span></button><button className="bag" onClick={()=>setBagOpen(true)}><ShoppingBag size={18}/><span>Bag</span><b>{bag.length}</b></button></div></header>
 <main id="home"><section className="hero"><div className="hero-copy"><p className="kicker"><Sparkles size={13}/> Curated luxury, within reach</p><h1>The pieces<br/><i>that complete it.</i></h1><p>Prestige perfumes, statement glares and beautifully made handbags from the labels you look for.</p><div className="hero-actions"><a className="button dark" href="#accessories">Shop the edit <ArrowUpRight size={16}/></a><button className="text-link" onClick={()=>setProductOpen(accessoryProducts[2])}>Discover the new bag <span>→</span></button></div><div className="flavour-note"><span>01</span><p>Featured this week<br/><b>Gucci, Zara &amp; Charles &amp; Keith</b></p></div></div><div className="hero-media"><div className="hero-shape one"></div><div className="hero-shape two"></div><img src={handbagImage} alt="Premium structured handbag from the Luxury Stop edit"/><div className="hero-sticker">Made to<br/><em>be noticed.</em><small>• the luxury edit •</small></div><button className="floating-product" onClick={()=>setProductOpen(accessoryProducts[2])}><i></i><span><b>Gabine Mini</b><small>View piece</small></span><Plus size={17}/></button></div></section>
 <section className="ritual-strip"><span>AUTHENTIC LABELS</span><span>✦</span><b>Curated in India</b><span>✦</span><span>INSURED DELIVERY</span></section>
 <section className="shop-section" id="shop"><div className="section-intro"><p className="kicker">A collection for the senses</p><h2>Quiet things,<br/><i>with presence.</i></h2><p>Every piece is made to leave a soft, considered impression.</p></div><div className="mood-grid"><button className="mood cocoa" onClick={()=>setCollectionOpen(true)}><span>For the<br/><i>sweet tooth</i></span><b>Confectionery <ArrowUpRight/></b></button><button className="mood rose" onClick={()=>setCollectionOpen(true)}><span>For the<br/><i>daily ritual</i></span><b>Bath &amp; body <ArrowUpRight/></b></button><button className="mood citrus" onClick={()=>setCollectionOpen(true)}><span>For the<br/><i>thoughtful gesture</i></span><b>Gift boxes <ArrowUpRight/></b></button></div><button className="collection-cta" onClick={()=>setCollectionOpen(true)}>View the full collection <ArrowUpRight size={17}/></button></section>
 <section className="shop-section" id="shop"><div className="section-intro"><p className="kicker">A collection for the senses</p><h2>Quiet things,<br/><i>with presence.</i></h2><p>Every piece is made to leave a soft, considered impression.</p></div><div className="mood-grid"><button className="mood cocoa" onClick={()=>setCollectionOpen(true)}><span>For the<br/><i>sweet tooth</i></span><b>Confectionery <ArrowUpRight/></b></button><button className="mood rose" onClick={()=>setCollectionOpen(true)}><span>For the<br/><i>daily ritual</i></span><b>Bath &amp; body <ArrowUpRight/></b></button><button className="mood citrus" onClick={()=>setCollectionOpen(true)}><span>For the<br/><i>thoughtful gesture</i></span><b>Gift boxes <ArrowUpRight/></b></button></div><button className="collection-cta" onClick={()=>setCollectionOpen(true)}>View the full collection <ArrowUpRight size={17}/></button></section>
 <section className="accessories-section" id="accessories"><div className="accessories-title"><p className="kicker">The luxury edit</p><h2>Objects of<br/><i>beautiful intent.</i></h2><p>A multi-brand edit of perfumes, glares and handbags, selected for the way they make an entrance.</p></div><div className="accessory-grid">{accessoryProducts.slice(0,3).map(item=><article className="accessory-card" key={item.id}><button className="accessory-image" onClick={()=>setProductOpen(item)}><span>{item.category}</span><img src={item.image} style={{objectPosition:item.position}} alt={item.name}/><b>View piece <ArrowUpRight size={15}/></b></button><div className="accessory-info"><div><small>{item.brand}</small><h3>{item.name}</h3><p>{item.type}</p></div><strong>₹{item.price.toLocaleString('en-IN')}</strong></div></article>)}</div><button className="collection-cta" onClick={goCollection}>Browse all products <ArrowUpRight size={17}/></button></section><section className="brand-index" id="brands"><p className="kicker">The label carousel</p><div className="brand-track">{[...brandLogos,...brandLogos].map(([name,logo],index)=><div className="brand-logo-tile" key={`${name}-${index}`}><img src={logo} alt={name}/></div>)}</div></section>
 <section className="shop-edit"><div className="edit-header"><div><p className="kicker">The material edit</p><h2>Made to linger,<br/><i>not to shout.</i></h2></div><p>Choose a ritual, discover its texture and take a more considered moment home.</p></div><div className="product-showcase"><div className="palette"><p>Choose a ritual</p>{products.map(p=><button key={p.id} onClick={()=>setSelected(p)} className={selected.id===p.id?'active':''}><i style={{background:p.color}}></i><span>{p.name.split(' ')[0]}</span></button>)}</div><div className="featured-product" style={{'--product-color':selected.color}}><div className="product-glow"></div><img src={selected.image} alt={selected.name}/><span className="rotate-copy">LUXURY STOP • MADE FOR SLOW MOMENTS • </span></div><div className="product-detail"><span className="edition">THE MATERIAL EDIT / 01</span><h3>{selected.name}</h3><p>{selected.type}</p><strong>₹{selected.price}</strong><div className="swatches"><i style={{background:selected.color}}></i><i style={{background:'#ede5d7'}}></i><i style={{background:'#6c725e'}}></i></div><button onClick={()=>add(selected)} className="button dark">Add to bag <Plus size={16}/></button></div></div></section>
 <section className="gift-banner" id="gifts"><div className="gift-visual"><div className="ribbon r1"></div><div className="ribbon r2"></div><div className="gift-card">A thoughtful<br/><i>little thing.</i><small>PERSONALISE YOUR GIFT</small></div></div><div className="gift-content"><p className="kicker">For every “this made me think of you”</p><h2>Gifting, <i>but make it personal.</i></h2><p>Choose the treats. Choose the feeling. Add a handwritten note. We’ll wrap the moment up just right.</p><button className="button light" onClick={()=>setGiftOpen(true)}>Start building <ArrowUpRight size={16}/></button></div></section>
 <section className="story" id="story"><p className="kicker">Luxury Stop, in a nutshell</p><div className="story-content"><h2>Luxury should feel<br/><i>easy to find.</i></h2><p>We bring together the accessories you’re looking for, with clear product details, thoughtful service and a more considered way to shop online.</p><a href="#accessories" className="text-link">Explore the edit <span>→</span></a></div></section>
 <section className="newsletter"><div><p className="kicker">A note from the good stuff department</p><h2>First dibs on<br/><i>beautiful things.</i></h2></div><form onSubmit={e=>{e.preventDefault();setMessage('Welcome to the good stuff ✦')}}><input required aria-label="Email address" type="email" placeholder="Your email address"/><button type="submit">Sign me up <ArrowUpRight size={17}/></button><small>Small drops, gift ideas and no boring emails.</small></form></section></main>
 <footer><a className="wordmark" href="#home">LUXURY <em>STOP</em></a><p>Perfumes · Glares · Handbags</p><div><a href="#accessories">Shop</a><a href="#brands">Brands</a><a href="#story">Instagram</a></div><small>© 2026 Luxury Stop. Curated for the details.</small></footer>
 {message&&<div className="toast">{message}<button onClick={()=>setMessage('')}><X size={16}/></button></div>}{giftOpen&&<GiftBuilder onClose={()=>setGiftOpen(false)} onAdd={g=>{add({...g,price:1495});setGiftOpen(false)}}/>}{bagOpen&&<BagDrawer bag={bag} onClose={()=>setBagOpen(false)} onRemove={index=>setBag(bag.filter((_,itemIndex)=>itemIndex!==index))}/>} {accountOpen&&<AccountPage onClose={()=>setAccountOpen(false)} onSuccess={text=>{setAccountOpen(false);setMessage(text)}}/>} {productOpen&&<ProductPage product={productOpen} onClose={()=>setProductOpen(null)} onAdd={quantity=>{for(let item=0;item<quantity;item+=1)add(productOpen);setProductOpen(null)}}/>}</>}
function GiftBuilder({onClose,onAdd}){const[step,setStep]=useState(0);const picks=[['Pick your box','The blush box','The saffron box'],['Add some joy','Raspberry bar','Rose cloud soap'],['Make it personal','For you, with love','Just because']];return <div className="modal-backdrop"><div className="gift-modal"><button className="close" onClick={onClose}><X/></button><p className="kicker">Build your gift / 0{step+1}</p><div className="progress"><i style={{width:`${(step+1)*33}%`}}></i></div><h2>{picks[step][0]}<br/><i>Make it feel like them.</i></h2><div className="gift-choices">{picks[step].slice(1).map((p,i)=><button key={p} className={i===0?'chosen':''}>{p}<Plus size={16}/></button>)}</div><button className="button dark" onClick={()=>step<2?setStep(step+1):onAdd({name:'Your custom joy box'})}>{step<2?'Continue':'Add my gift box'}<ArrowUpRight size={16}/></button></div></div>}
function BagDrawer({bag,onClose,onRemove}){const total=bag.reduce((sum,item)=>sum+(item.price||0),0);return <div className="bag-overlay" onClick={onClose}><aside className="bag-drawer" onClick={event=>event.stopPropagation()}><div className="bag-title"><div><p className="kicker">Your selection</p><h2>Bag <i>({bag.length})</i></h2></div><button className="close" onClick={onClose}><X/></button></div>{bag.length?<><div className="bag-items">{bag.map((item,index)=><div className="bag-item" key={`${item.name}-${index}`}><div className="bag-thumb" style={{background:item.color}}>{item.image&&<img src={item.image} alt=""/>}</div><div><h3>{item.name}</h3><p>{item.type||'Curated especially for you'}</p><strong>₹{item.price.toLocaleString('en-IN')}</strong></div><button className="remove" onClick={()=>onRemove(index)}>Remove</button></div>)}</div><div className="bag-summary"><p><span>Subtotal</span><strong>₹{total.toLocaleString('en-IN')}</strong></p><small>Complimentary wrapping included.</small><button className="button dark">Proceed to checkout <ArrowUpRight size={16}/></button></div></>:<div className="empty-bag"><ShoppingBag size={28}/><h3>Your bag is waiting.</h3><p>There’s room for a lovely little thing.</p><button className="button dark" onClick={onClose}>Explore collection</button></div>}</aside></div>}
function AccountPage({onClose,onSuccess}){const[mode,setMode]=useState('signin');const signUp=mode==='signup';return <div className="account-page"><div className="account-visual"><img src={heroImage} alt="Luxury Stop’s evening collection"/><div className="account-quote"><span>THE PRIVATE EDIT</span><p>“Good things,<br/><i>remembered.”</i></p><small>MEMBERS RECEIVE FIRST ACCESS TO NEW DROPS</small></div></div><section className="account-panel"><button className="account-close" onClick={onClose}><X size={20}/><span>Close</span></button><a className="wordmark" href="#home">LUXURY <em>STOP</em></a><div className="account-form"><p className="kicker">{signUp?'Begin your private edit':'Welcome back'}</p><h1>{signUp?'A little more,':'The good things,'}<br/><i>{signUp?'just for you.':'saved for you.'}</i></h1><p className="account-intro">{signUp?'Create an account for saved rituals, considered gifting and first access to new collections.':'Sign in to find your saved rituals, gift notes and previous orders.'}</p><form onSubmit={event=>{event.preventDefault();onSuccess(signUp?'Your private edit is ready ✦':'Welcome back to Luxury Stop ✦')}}>{signUp&&<label>Full name<input required placeholder="Your name"/></label>}<label>Email address<input required type="email" placeholder="you@example.com"/></label><label>Password<input required type="password" placeholder="••••••••"/></label>{!signUp&&<button type="button" className="forgot">Forgot password?</button>}<button className="button dark" type="submit">{signUp?'Create my account':'Sign in'} <ArrowUpRight size={16}/></button></form><div className="account-switch"><span>{signUp?'Already have an account?':'New to Luxury Stop?'}</span><button onClick={()=>setMode(signUp?'signin':'signup')}>{signUp?'Sign in':'Create an account'} →</button></div></div><div className="account-footer"><span>PRIVATE EDITS</span><i>✦</i><span>THOUGHTFUL GIFTING</span></div></section></div>}
function CollectionPage({onClose,onAdd}){const[filter,setFilter]=useState('All');const items=[...products,{id:4,name:'Rosewater Bonbons',type:'White chocolate / 9 pieces',price:745,color:'#9b6460',image:ritualImage,group:'Sweets'},{id:5,name:'Moss Bath Soak',type:'Mineral salt soak / 280g',price:645,color:'#68705f',image:heroImage,group:'Rituals'},{id:6,name:'A Note, In Ivory',type:'Gift set / ready to send',price:1695,color:'#aa957f',image:ritualImage,group:'Gifting'}].map((item,index)=>({...item,group:item.group||(['Sweets','Rituals','Gifting'][index])}));const visible=filter==='All'?items:items.filter(item=>item.group===filter);return <div className="collection-page"><header className="collection-header"><a className="wordmark" href="#home">LUXURY <em>STOP</em></a><button onClick={onClose}><X size={19}/><span>Close collection</span></button></header><section className="collection-hero"><div><p className="kicker">The house collection / 01</p><h1>Things worth<br/><i>returning to.</i></h1><p>A considered curation of sweets, daily rituals and gestures made to say more.</p></div><div className="collection-hero-image"><img src={heroImage} alt="Luxury Stop collection"/><span>SCROLL TO DISCOVER</span></div></section><section className="collection-body"><div className="collection-toolbar"><p>{visible.length} pieces, collected slowly</p><div>{['All','Sweets','Rituals','Gifting'].map(item=><button key={item} className={filter===item?'selected':''} onClick={()=>setFilter(item)}>{item}</button>)}</div></div><div className="collection-grid">{visible.map((item,index)=><article className={`collection-card card-${index%3}`} key={item.id}><div className="collection-image" style={{background:item.color}}><span>{item.group}</span><img src={item.image} alt={item.name}/><button onClick={()=>onAdd(item)} aria-label={`Add ${item.name}`}><Plus size={17}/></button></div><div className="collection-detail"><div><h3>{item.name}</h3><p>{item.type}</p></div><strong>₹{item.price.toLocaleString('en-IN')}</strong></div></article>)}</div></section></div>}
function CatalogPage({onClose,onView}){
 const [filter,setFilter]=useState('All')
 const [visibleCount,setVisibleCount]=useState(12)
 const categories=['All','Perfumes','Glares','Handbags','Watches']
 const filtered=accessoryProducts.filter(item=>filter==='All'||item.category===filter)
 const best=accessoryProducts.filter((_,index)=>[0,2,4,6,10].includes(index))
 const favourites=accessoryProducts.filter((_,index)=>[1,3,5,8,9].includes(index))
 const Card=({item})=><article className="catalog-card">
  <button className="catalog-image" onClick={()=>onView(item)}><img src={item.image} style={{objectPosition:item.position}} alt={item.name}/><span>{item.category}</span><b>View piece <ArrowUpRight size={15}/></b></button>
  <div><small>{item.brand}</small><h3>{item.name}</h3><p>{item.type}</p><strong>₹{item.price.toLocaleString('en-IN')}</strong></div>
 </article>
 return <div className="catalog-page">
  <header className="catalog-header"><a className="wordmark" href="#home">LUXURY <em>STOP</em></a><button onClick={onClose}><X size={19}/><span>Back home</span></button></header>
  <section className="catalog-intro"><p className="kicker">Luxury Stop / All products</p><h1>Find your next<br/><i>favourite thing.</i></h1><p>Explore our complete edit of designer perfumes, statement glares, iconic handbags and watches.</p></section>
  <section className="catalog-content">
   <section className="catalog-section catalog-all" id="all">
    <div className="catalog-section-heading"><div><p className="kicker">The complete Luxury Stop edit</p><h2>All <i>pieces.</i></h2></div><span>{filtered.length} products</span></div>
    <div className="catalog-filter"><span>Filter by category</span><div>{categories.map(category=><button key={category} className={filter===category?'active':''} onClick={()=>{setFilter(category);setVisibleCount(12)}}>{category}</button>)}</div></div>
    <div className="catalog-grid">{filtered.slice(0,visibleCount).map(item=><Card key={item.id} item={item}/>)}</div>
    {visibleCount<filtered.length&&<button className="load-more" onClick={()=>setVisibleCount(visibleCount+12)}>Load more pieces <ArrowUpRight size={16}/></button>}
   </section>
   <CatalogSection id="best" eyebrow="The edit, as chosen" title="Best <i>sellers.</i>" items={best} Card={Card}/>
   <CatalogSection id="favourites" eyebrow="A little insider knowledge" title="Star <i>favourites.</i>" items={favourites} Card={Card}/>
   <section className="style-spotlight"><div className="spotlight-image"><img src={spotlightImage} alt="Fashion campaign talent styling black sunglasses and handbag"/></div><div className="spotlight-copy"><p className="kicker">Style spotlight / campaign concept</p><h2>“The piece that<br/><i>does the talking.”</i></h2><p>Our campaign muse styles the Obsidian Frame with a clean black bag—the kind of look that makes an ordinary entrance feel intentional.</p><div><span>★★★★★</span><small>DEMO CAMPAIGN REVIEW · TO BE REPLACED WITH A LICENSED PARTNER QUOTE</small></div><button className="button dark" onClick={()=>onView(accessoryProducts[1])}>Shop the look <ArrowUpRight size={16}/></button></div></section>
  </section>
 </div>
}
function CatalogSection({id,eyebrow,title,items,Card}){return <section className="catalog-section" id={id}><div className="catalog-section-heading"><div><p className="kicker">{eyebrow}</p><h2 dangerouslySetInnerHTML={{__html:title}}/></div><span>{items.length} pieces</span></div><div className={id==='all'?'catalog-grid':'catalog-row'}>{items.map(item=><Card key={item.id} item={item}/>)}</div></section>}
function ProductPage({product,onClose,onAdd}){
 const [quantity,setQuantity]=useState(1)
 const [view,setView]=useState(0)
 const views=[
  {label:'Front view',scale:1,position:product.position},
  {label:'Dial detail',scale:1.28,position:product.position},
  {label:'Finish detail',scale:1.12,position:product.position}
 ]
 const activeView=views[view]
 const previous=()=>setView(current=>(current+views.length-1)%views.length)
 const next=()=>setView(current=>(current+1)%views.length)
 return <div className="product-page">
  <header className="product-header"><a className="wordmark" href="#home">LUXURY <em>STOP</em></a><button onClick={onClose}><X size={19}/><span>Back to shop</span></button></header>
  <main className="product-layout">
   <section className={`product-gallery crop-${product.crop}`}>
    <div className={`main-product-image crop-${product.crop} gallery-view-${view}`}>
     <img src={product.image} alt={`${product.name} — ${activeView.label}`}/>
     <span>{activeView.label}</span>
     <button className="gallery-arrow previous" onClick={previous} aria-label="Previous product image">←</button>
     <button className="gallery-arrow next" onClick={next} aria-label="Next product image">→</button>
    </div>
    <div className={`gallery-thumbnails crop-${product.crop}`} aria-label="Product image gallery">{views.map((item,index)=><button key={item.label} className={view===index?'active':''} onClick={()=>setView(index)} aria-label={item.label}><img className={`gallery-thumb-view-${index}`} src={product.image} alt=""/></button>)}</div>
    <div className="gallery-note"><p>AUTHENTIC PRODUCT</p><span>Complimentary insured delivery<br/>on this piece.</span></div>
   </section>
   <section className="product-buy"><p className="kicker">{product.brand} / {product.category}</p><h1>{product.name}</h1><p className="product-type">{product.type}</p><h2>₹{product.price.toLocaleString('en-IN')}</h2><p className="product-description">{product.details}</p><div className="product-stock"><span>✓ In stock</span><span>100% authentic</span></div><div className="quantity-row"><span>Quantity</span><div><button onClick={()=>setQuantity(Math.max(1,quantity-1))}>−</button><b>{quantity}</b><button onClick={()=>setQuantity(quantity+1)}>+</button></div></div><button className="button dark product-add" onClick={()=>onAdd(quantity)}>Add to bag <span>₹{(product.price*quantity).toLocaleString('en-IN')}</span><ArrowUpRight size={16}/></button><div className="product-promises"><span>✓ Authenticity verified</span><span>✓ Signature gift wrapping</span><span>✓ 7-day returns</span></div></section>
  </main>
 </div>
}
