import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import './bag.css'
import './account.css'
import './collection.css'
import './products.css'
import './product-detail.css'
import './catalog.css'
import './catalog-layout.css'
import './catalog-scale.css'
import './spotlight.css'
import './brand-carousel.css'
import './marketplace.css'
import './brand-logos.css'
import './mobile-fix.css'
import App from './App'
createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>)
